#(a)
f_a_xy = lambda x, y: x * x + x * y ** 3
print(f_a_xy(-1, 1))
print(f_a_xy(0, 0))
print(f_a_xy(2, 3))
print(f_a_xy(-3, -2))
#(b)
f_b_xyz = lambda x, y, z: (x - y) / (y ** 2 + z ** 2)
print(f_b_xyz(3, -1, 2))
print(f_b_xyz(1, 1/2, 1/4))
print(f_b_xyz(0, -1/3, 0))
print(f_b_xyz(2, 2, 100))