import sympy as sp
x, y = sp.symbols('x, y')
#(a)
f = x * sp.sin(y) + y * sp.sin(x) + x * y
dfx = sp.diff(f, x)
df_xy = sp.diff(dfx, y)
print(df_xy)
df_yx = sp.diff(sp.diff(f, y), x)
print(df_yx)
#(b)
f = sp.log(2 * x + 3 * y)
dfx = sp.diff(f, x)
df_xy = sp.diff(dfx, y)
print(df_xy)
df_yx = sp.diff(sp.diff(f, y), x)
print(df_yx)
#(c)
f = x * y ** 2 + x ** 2 * y ** 3 + x ** 3 * y ** 4
dfx = sp.diff(f, x)
df_xy = sp.diff(dfx, y)
print(df_xy)
df_yx = sp.diff(sp.diff(f, y), x)
print(df_yx)
#(d)
f = sp.exp(x) + x * sp.log(y) + y * sp.log(x)
dfx = sp.diff(f, x)
df_xy = sp.diff(dfx, y)
print(df_xy)
df_yx = sp.diff(sp.diff(f, y), x)
print(df_yx)