import sympy as sp
x, y = sp.symbols('x, y')
#(a)
print("cau a")
fa = y*y*(x**4)*sp.exp(x) + 2
dfa_y = sp.diff(fa, y, 3)
dfa_y_x = sp.diff(dfa_y, x, 2)
print("Đạo hàm bâc 5 của fa(x, y) = ", dfa_y_x)
#(b)
print("cau b")
fb = y**4 + y*(sp.sin(x) - (y**4))
dfb_y = sp.diff(fb, y, 3)
dfb_y_x = sp.diff(dfb_y, x, 2)
print("Đạo hàm bâc 5 của fb(x, y) = ", dfb_y_x)
#(c)
print("cau c")
fc = x**5 +5*x*y +sp.sin(x) + 7*sp.exp(x)
dfc_y = sp.diff(fc, y, 3)
dfc_y_x = sp.diff(dfc_y, x, 2)
print("Đạo hàm bâc 5 của fc(x, y) = ", dfc_y_x)
#(d)
print("cau d")
fd = x * sp.exp(y ** 4 / 2)
dfd_y = sp.diff(fb, y, 3)
dfd_y_x = sp.diff(dfb_y, x, 2)
print("Đạo hàm bâc 5 của fd(x, y) = ", dfd_y_x)