import sympy as sp
x, t, z = sp.symbols('x y z')
#(a)
f = 4 - x * x
dfa = sp.diff(f, x)
print("1a - Derivative of f(x) = ", dfa)
#(b)
f = (x - 1) ** 2 + 1
dfb = sp.diff(f, x)
print("1b - Derivative of f(x) = ", dfb)
#(c)
f = 1 / (t ** 2)
dfc = sp.diff(f, t)
print("1c - Derivative of f(x) = ", dfc)
#(d)
f = (1 - z) / (2 * z)
dfd = sp.diff(f, z)
print("1d - Derivative of f(x) = ", dfd)
#(e)
f = (3 * z) ** (1 / 2)
dfe = sp.diff(f, z)
print("1e - Derivative of f(x) = ", dfe)
#(f)
f = (2 * z + 1) ** (1 / 2)
dff = sp.diff(f, z)
print("1f - Derivative of f(x) = ", dff)