import sympy as sp
t = sp.symbols("t")
f_H = sp.sqrt(t + 1) + 5*t**(1/3)
#(a)
h1 = f_H.subs(t, 0)
h2 = f_H.subs(t, 4)
h3 = f_H.subs(t, 8)
print("Tree's height when t = 0 is", h1)
print("Tree's height when t = 4 is", h2)
print("Tree's height when t = 8 is", h3)
#(b)
fin_H = sp.integrate(f_H, (t, 0, 8))
avg_H = 1/(8 - 0)*fin_H.evalf()
print("Tree's average = ", avg_H)